version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 20
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns:
          - "*"
