apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-injected-certs
  namespace: acm-policy-helper
  labels:
    app.kubernetes.io/name: acm-policy-helper
    config.openshift.io/inject-trusted-cabundle: "true"
