apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-policy-helper
  namespace: acm-policy-helper
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"acm-policy-helper"}}
  labels:
    app.kubernetes.io/name: acm-policy-helper
